version: '3.8'

services:
  app:
    build: .
    container_name: basic-image-bed
    restart: unless-stopped
    ports:
      - "28123:8080"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xmx512m -Xms256m
