
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: always
      schema-locations: classpath:init.sql
      platform: mysql
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sunyong.imagebed.mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.sunyong.imagebed.mapper: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html

image_bed:
  debug_mode: true
  server_url: ${SERVER_URL}
  allow_size_kb: ${ALLOW_SIZE_KB}
  allow_suffix: ${ALLOW_SUFFIX}
  local_path: ${LOCAL_PATH}
  auth:
    allow-register: ${AUTH_ALLOW_REGISTER}
    allow-guest: ${AUTH_ALLOW_GUEST}

server:
  port: 8080