server:
  port: 8080

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#  devtools:
#    restart:
#      enabled: false  # 启用热重启
#      additional-paths: # 额外监控的路径
#        - ../bed-base/src/main/java
#        - src/main/java
#      livereload:
#        enabled: false
#      exclude: static/**,public/**  # 排除不需要监控的文件

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  cache:
    disabled: false
